[BUG] Bad Request: (redirect_uri_mismatch)
gogixweb/bahea-cal pull request #101
Opened 2024-08-19 19:51 UTC by ronicarn

modiquei o link do views.py

2024-08-19 21:10 UTC, ivancrneto commented
Precisa adicionar `BASE_APP_URL` no `settings.py` também, da mesma forma que essa linha aqui: https://github.com/gogixweb/bahea-cal/blob/main/webapp/settings.py#L39

2024-08-19 21:10 UTC, ivancrneto requested changes

2024-08-19 21:10 UTC, ivancrneto commented on api/views.py
> +    flow = Flow.from_client_config(config, scopes=SCOPES,redirect_uri=DJANGO_BASE_APP_URL)
tem que pegar do settings:

```suggestion
    flow = Flow.from_client_config(config, scopes=SCOPES,redirect_uri=settings.BASE_APP_URL)
```

2024-08-20 21:39 UTC, ronicarn commented
corrigir o erro do link da views.py

2024-08-21 17:58 UTC, ivancrneto approved these changes

2024-08-21 17:58 UTC, merged