Updated README.md and requirements-dev.txt
gogixweb/bahea-cal pull request #17
Opened 2024-04-11 18:35 UTC by jacks0nsilva

- Instructions on how to run the project updated in README.md

- ipdb version modified in requirements-dev.txt

2024-04-12 16:52 UTC, ivancrneto requested changes

2024-04-12 16:52 UTC, ivancrneto commented on README.md
> +DJANGO_CALENDAR_NAME_PREFIX="(dev) "
Colocar aqui os passos
```
python manage.py migrate
python manage.py collectstatic
```

2024-04-16 20:21 UTC, jacks0nsilva commented on README.md
> +DJANGO_CALENDAR_NAME_PREFIX="(dev) "
Passos adicionados

2024-04-17 15:38 UTC, ivancrneto approved these changes

2024-04-17 15:38 UTC, merged