first commit + react frontend
gogixweb/bahea-cal pull request #18
Opened 2024-04-11 23:59 UTC by Kauannery

Adição de Pasta frontend que contém o App React + Componentes do react

2024-04-12 16:50 UTC, ivancrneto requested changes

2024-04-12 16:50 UTC, ivancrneto commented on webapp/api/app.py
> +        uvicorn.run(app, host='0.0.0.0', port = 7777)
Coloca essa pasta /api/ na raiz, fora de webapp

2024-04-12 16:50 UTC, ivancrneto commented on frontend/my-react-app/src/assets/react.svg
precisa desse arquivo?

2024-04-12 16:50 UTC, ivancrneto commented on frontend/my-react-app/public/vite.svg
Precisa desse arquivo?

2024-04-12 16:50 UTC, ivancrneto commented on frontend/my-react-app/src/App.jsx
É possível remover essa pasta /my-react-app/ e mover os arquivos uma pasta acima?

2024-04-14 02:11 UTC, Kauannery commented on frontend/my-react-app/public/vite.svg
É a só imagem mesmo

2024-04-15 13:17 UTC, Kauannery commented
Alterações realizadas

2024-04-16 17:08 UTC, ivancrneto approved these changes

2024-04-16 17:08 UTC, merged