Alterações no pyproject
gogixweb/bahea-cal pull request #19
Opened 2024-04-16 12:57 UTC by Kauannery

Pacotes  instalados:

psycopg2
gunicorn
gevent

2024-04-17 15:36 UTC, ivancrneto requested changes

2024-04-17 15:36 UTC, ivancrneto commented on requirements.txt
desfaz as alterações desse arquivo. Vc pode fazer isso assim:
```
git revert 5b0ab0c374e5a75840053ebfc2214d01048e0dc3
git commit ...
```

2024-04-22 16:16 UTC, Kauannery commented
Alterações desfeitas como pedido

2024-04-26 18:52 UTC, ivancrneto approved these changes

2024-04-26 18:52 UTC, ivancrneto commented
@Kauannery deu conflito aqui

2024-04-26 18:55 UTC, Kauannery commented
qual o conflito?

2024-04-29 13:06 UTC, ivancrneto commented
sim, tem que fazer um merge de main na tua branch localmente pra resolver o conflito.

2024-04-29 18:14 UTC, ivancrneto commented on pyproject.toml
> +  "gunicorn==23.9.1",
```suggestion
  "gunicorn==23.9.1",
  "beautifulsoup4==",
```

2024-04-29 20:19 UTC, Kauannery commented
Merge na Branch Main feito 
Package.json atualizado 
beautifulsoup4 e pacotes adicionados 

Obs.: Foi realizado da branch pacotes-pyproject

2024-05-02 16:37 UTC, ivancrneto approved these changes

2024-05-02 16:37 UTC, merged