PR task "Criar página inicial em React"
gogixweb/bahea-cal pull request #28
Opened 2024-04-22 19:23 UTC by Kauannery

2024-04-26 18:44 UTC, Kauannery commented
fluxo de login para o google calendar feito

2024-04-29 13:10 UTC, ivancrneto requested changes

2024-04-29 13:10 UTC, ivancrneto commented on frontend/src/App.jsx
> +// export default App;
poderia remover esse código comentado?

2024-04-29 13:10 UTC, ivancrneto commented on frontend/src/assets/flamengo1.png
por que tem dois logos do Flamengo? Eu odeio o Flamengo, quanto menos, melhor haha

2024-04-29 13:10 UTC, ivancrneto commented on frontend/src/index.css
> +  padding: 5px;
não sou lá essas coisas de FE, mas acho melhor usar `em` do que `px`

2024-04-29 13:10 UTC, ivancrneto commented on frontend/src/index.css
> +  }
por que essa entrada tá vazia?

2024-04-29 14:40 UTC, Kauannery commented
Bom dia, excluido a outra imagem do flamengo kkk
ia colocar algumas coisas no media 
Tive que alterar o app.jsx pra funcionar os botões de login ao calendário 
Vou criar a outra página para a escolha do clube

2024-04-30 12:06 UTC, ivancrneto commented
@Kauannery ainda ta faltando o package.json

2024-04-30 22:26 UTC, ivancrneto approved these changes

2024-04-30 22:26 UTC, merged