Create english readme
gogixweb/bahea-cal pull request #3
Opened 2018-11-06 19:52 UTC by tyronedamasceno

Create a version of README in english.

2018-11-09 13:24 UTC, ivancrneto requested changes

2018-11-09 13:24 UTC, ivancrneto commented on README.md
> +Bahea Calendar is a project that will add to your google calendar the schedule of your favorite soccer team games!
"...that adds the standings of your favorite soccer team games to your google calendar!"

Sounds a bit better

2018-11-09 13:24 UTC, ivancrneto commented on README.md
> +Also, you need to create a project to access the google calendar API. You can do it accessing the google's [developers console](https://console.developers.google.com/). When it's done, download the J
You can do it *by* accessing

rename it ~with~ *to*

2018-11-12 13:38 UTC, tyronedamasceno commented on README.md
> +Also, you need to create a project to access the google calendar API. You can do it accessing the google's [developers console](https://console.developers.google.com/). When it's done, download the J
Done

2018-11-12 13:38 UTC, tyronedamasceno commented on README.md
> +Bahea Calendar is a project that will add to your google calendar the schedule of your favorite soccer team games!
Done

2018-11-12 16:49 UTC, ivancrneto approved these changes
LGTM

2018-11-12 16:53 UTC, merged