Add instructions to readme
gogixweb/bahea-cal pull request #36
Opened 2024-04-26 18:43 UTC by ruanclaudio

Refiz as alterações que ficaram em aberto da task do Jackson. no README e nos arquivos settings.py / urls.py

2024-04-29 13:17 UTC, ivancrneto requested changes

2024-04-29 13:17 UTC, ivancrneto commented on webapp/secrets.py
> +    if "dev" in secret_name:
em vez de fazer esse `if`, é melhor mover o bloco:
```python
session = boto3.session.Session()
    client = session.client(
        service_name='secretsmanager',
        region_name=region_name
    )
```
pra dentro to `try`

2024-04-29 13:17 UTC, ivancrneto commented on core/views.py
> +    state = request.GET.get("state")
```suggestion
    state = request.session.get("state") or request.GET.get("state")
```

2024-04-29 13:17 UTC, ivancrneto commented on webapp/secrets.py
> +            raise e_ from e_
`raise e_ from e_` vai dar pau. Tem que ser `raise e_ from e`

2024-04-29 19:11 UTC, ruanclaudio commented
Ivan, eu fiz as alterações, mas quando roda o server aqui ele dá error ```NoCredentialsError at /calendar/init/ ``` quando clica no Bahia e antes com o if else tava rodando normal.

2024-04-30 21:03 UTC, ivancrneto approved these changes

2024-04-30 21:03 UTC, merged