feat: add pdm and update requirements.txt
gogixweb/bahea-cal pull request #37
Opened 2024-04-26 19:25 UTC by ruanclaudio

2024-04-29 13:20 UTC, ivancrneto requested changes

2024-04-29 13:20 UTC, ivancrneto commented on pyproject.toml
> +description = "Django project template managed by PDM"
muda essa linha de volta

2024-04-29 13:20 UTC, ivancrneto commented on pyproject.toml
> +requires-python = "==3.12.*"
coloca acima de 3.10 aqui, eu acho que em produção no momento é 3.10

2024-04-29 13:20 UTC, ivancrneto commented on pyproject.toml
> +    {name = "Ruan", email = "ruanclaudio4@gmail.com"},
coloca o nome e o e-mail de todo mundo

2024-04-29 17:39 UTC, ruanclaudio commented
Realizei as alterações que você demarcou.
https://github.com/orgs/gogixweb/projects/2/views/1?pane=issue&itemId=59435159

2024-04-30 12:09 UTC, ivancrneto requested changes

2024-04-30 12:09 UTC, ivancrneto commented on pyproject.toml
> +
`Kauan Nery`, e coloca em ordem alfabética

2024-05-02 17:13 UTC, ivancrneto approved these changes

2024-05-02 17:13 UTC, merged