configuracao google-calendar issue #43
gogixweb/bahea-cal pull request #47
Opened 2024-05-07 19:41 UTC by Kauannery

Issue #43 
Alterações no app React para que o serviço de api Google Calendar busque usuário de login atráves das contas google 
Objetivo : Fzer login usando contas google
Alteraões feitas :
Funções 
.eslintrc.cjs 
modificações em .env

2024-05-08 17:46 UTC, ivancrneto requested changes

2024-05-08 17:46 UTC, ivancrneto commented on frontend/src/Login.jsx
> +    console.log(process.env.REACT_APP_GOOGLE_CLIENT_ID);
remove esse console.log

2024-05-08 17:46 UTC, ivancrneto commented on frontend/src/Login.jsx
> +            console.log('Não Autenticado com sucesso!');
remove

2024-05-08 17:46 UTC, ivancrneto commented on frontend/src/Login.jsx
> +            console.log('Autenticado com sucesso!');
remove

2024-05-08 19:16 UTC, Kauannery commented
console.log excluidos

2024-05-10 17:33 UTC, ivancrneto approved these changes

2024-05-10 17:33 UTC, merged