update: settings.py to run with cors settings
gogixweb/bahea-cal pull request #62
Opened 2024-05-29 18:32 UTC by ruanclaudio

Issue: #61

2024-06-01 00:59 UTC, ivancrneto commented on webapp/settings.py
> +    "core.middleware.CustomCorsMiddleware",
cade esse arquivo e classe na PR?

2024-06-01 00:59 UTC, ivancrneto requested changes

2024-06-01 00:59 UTC, ivancrneto commented on webapp/settings.py
> +# ]
pode retirar esses comentarios?

2024-06-03 16:40 UTC, ruanclaudio commented on webapp/settings.py
> +    "core.middleware.CustomCorsMiddleware",
quais arquivos e classe?

2024-06-03 17:28 UTC, ruanclaudio commented on webapp/settings.py
> +    "core.middleware.CustomCorsMiddleware",
acabei de adicionar

2024-06-03 23:46 UTC, ivancrneto requested changes

2024-06-03 23:46 UTC, ivancrneto commented on core/middleware.py
> +        return response
remove esses comentários
```suggestion
class CustomCorsMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        response = self.get_response(request)
        response["Access-Control-Allow-Origin"] = "*"
        response["Access-Control-Allow-Headers"] = "*"

        return response

```

2024-06-05 20:51 UTC, ivancrneto approved these changes

2024-06-05 20:51 UTC, merged