Show userprofile endpoint
gogixweb/bahea-cal pull request #79
Opened 2024-06-18 17:33 UTC by ruanclaudio

this PR creates a new endpoint whose purpose is to return the user's profile information. The endpoint still needs to be tested and is not fully functional, this is just the first stage of it.

2024-06-18 20:02 UTC, fmotaf commented on api/views.py
> +FULL_SECRET_PATH = 'C:/Users/ruanc/OneDrive/Documentos/Workspace/bahea-cal/webapp/secrets.json'
Acho que pode definir o root path usando Pathlib, exemplo:
```
  from pathlib import Path
  import os 
  ROOT_FOLDER = Path().resolve().parent
  FULL_SECRET_PATH = os.path.join(ROOT_FOLDER, "webapp", "secrets.json")
```
porque se estiver assim pode não funcionar pra outra máquina que tenha um path diferente

2024-06-18 20:09 UTC, ivancrneto requested changes

2024-06-18 20:09 UTC, ivancrneto commented on api/views.py
> +FULL_SECRET_PATH = 'C:/Users/ruanc/OneDrive/Documentos/Workspace/bahea-cal/webapp/secrets.json'
remove isso, precisa ser uma var de ambiente

2024-06-18 20:09 UTC, ivancrneto commented on api/views.py
> +    print("cred= ", creds)
remove

2024-06-18 20:09 UTC, ivancrneto commented on users/serializer.py
> +    user_photo = serializers.ImageField()
pode ser só email e photo, a gente já sabe que é do user

2024-06-18 20:09 UTC, ivancrneto commented on users/serializer.py
> +    choiced_teams = serializers.DictField(child=serializers.ListField(child=serializers.EmailField()))
melhor `selected_teams`

2024-06-18 20:09 UTC, ivancrneto commented on api/views.py
> +    calendar_service = build('calendar', 'v3', credentials=creds)
```suggestion
    user_creds = UserCredential.objects.get(user=request.user)
    creds = Credentials.from_user_credentials(user_credentials)
    
    calendar_service = googleapiclient.discovery.build('calendar', 'v3', credentials=creds)
```

2024-06-18 20:09 UTC, ivancrneto commented on users/serializer.py
> +    )
pq um `DictField` ?

2024-06-19 17:00 UTC, ruanclaudio commented on api/views.py
> +    calendar_service = build('calendar', 'v3', credentials=creds)
Esse pedaço é para eu remover o bloco da linha 80 até a 91? e substituir pela de baixo n é?

2024-06-19 17:02 UTC, ruanclaudio commented on users/serializer.py
> +    )
Pensei na possibilidade do usuário selecionar vários horários que qr ser alertado e aí seria uma lista ou um dicionário com o tempo até o alerta, 2 dias antes, 30 minutos, 2 horas etc

2024-06-19 21:13 UTC, ivancrneto commented on users/serializer.py
> +    )
pode ser

2024-06-19 21:14 UTC, ivancrneto requested changes

2024-06-19 21:14 UTC, ivancrneto commented on users/serializer.py
> +    )
muda pra `notify_before` (pra representar que o usuário será notificado X horas/dias/etc antes da partida.

2024-06-19 21:15 UTC, ivancrneto commented on api/views.py
> +    creds = Credentials.from_user_credentials(user_creds)
parece estar certo agora. Testou com essa mudança?

2024-06-27 19:56 UTC, closed without merging