form settings create issue
gogixweb/bahea-cal pull request #83
Opened 2024-06-25 18:58 UTC by Kauannery

issue #35

2024-06-28 22:42 UTC, ivancrneto requested changes

2024-06-28 22:42 UTC, ivancrneto commented on frontend/src/FormSettings.jsx
> +    const [outroClube, setOutroClube] = useState(false);
Por que essas variáveis estão em portugues?

2024-06-28 22:42 UTC, ivancrneto commented on frontend/src/index.jsx
> +      path: "/formulario",
Por que portugues?

2024-06-28 22:42 UTC, ivancrneto commented on frontend/src/FormSettings.jsx
> +        /// Aqui você pode adicionar a lógica para lidar com o envio do formulário
Não entendi esse comentário?

2024-07-01 16:39 UTC, Kauannery commented
Vou alterar para inglês tudo 
Quanto a parte do comentário devo excluir ali vai ser o envio do formulário + A requisição PUT

2024-07-01 22:45 UTC, ivancrneto commented on frontend/src/index.jsx
> +  },
que tal isso?
```suggestion
  {
      path: "/usersettings/edit",
      element: <UserSettingsForm.jsx/>,
  },
```

2024-07-03 16:24 UTC, ivancrneto commented on frontend/src/FormSettings.jsx
> +        console.log({ firstName, lastName, calendar, notification, club, anotherClub });
pode remover esse `log`

2024-07-03 16:25 UTC, ivancrneto commented on frontend/src/FormSettings.jsx
> +console.log(React)
tem como tirar?

2024-07-10 19:11 UTC, ivancrneto approved these changes

2024-07-10 19:12 UTC, merged