feat: new modify for user_info endpoint
gogixweb/bahea-cal pull request #85
Opened 2024-06-27 19:58 UTC by ruanclaudio

2024-06-28 22:54 UTC, ivancrneto requested changes

2024-06-28 22:54 UTC, ivancrneto commented on api/views.py
> +FULL_SECRET_PATH = os.path.join(ROOT_FOLDER, "webapp", "secrets.json")
essas variávies tão sendo usadas?

2024-06-28 22:54 UTC, ivancrneto commented on api/views.py
> +    credential = UserCredential.objects.get(id=1)
```suggestion
    credential = UserCredential.objects.filter(user=request.user)
```

2024-06-28 22:54 UTC, ivancrneto commented on api/views.py
> +    response = requests.get(f"{URL_GOOGLE_USER_DATA}{creds}")
```suggestion
    user_service = UserService.from_credentials(credentials)
    response = user_service.remote()
```

2024-06-28 22:54 UTC, ivancrneto commented on users/serializer.py
> +class UserInfoSerializer(serializers.Serializer):
Esse serializer está sendo usado?

Ao invés de fazer `JsonResponse((response.content)` na view, é necessário passar o content para o serializer e depois passar `serializer.data` para o `JsonResponse`

2024-07-01 16:56 UTC, ruanclaudio commented on api/views.py
> +FULL_SECRET_PATH = os.path.join(ROOT_FOLDER, "webapp", "secrets.json")
não, estavam antes mas depois q mudou a lógica parou de ser usada.

2024-07-01 17:16 UTC, ruanclaudio commented on users/serializer.py
> +class UserInfoSerializer(serializers.Serializer):
Não, inicialmente eu tava tentando utilizar ele. Mas esse endpoint n está mais usando, n sei se será usado futuramente tbm.

2024-07-03 16:28 UTC, ivancrneto approved these changes

2024-07-03 16:28 UTC, merged