service local storage
gogixweb/bahea-cal pull request #88
Opened 2024-07-09 19:25 UTC by Kauannery

2024-07-12 19:17 UTC, ivancrneto requested changes

2024-07-12 19:17 UTC, ivancrneto commented on frontend/src/UserSettings.jsx
> +              "Authorization": "Token cc667d866d62ce770fd90736daa5a8a36d6db6cd",
por que esse token tá hard-coded?

2024-07-12 19:17 UTC, ivancrneto commented on frontend/src/Login.jsx
> +    const navigate = useNavigate();
nit: tá desalinhado

2024-07-12 19:17 UTC, ivancrneto commented on frontend/src/Login.jsx
> +      // navigate('/outra-pagina');
poderia remover esse comentário?

2024-07-12 19:17 UTC, ivancrneto commented on frontend/src/Login.jsx
> +      console.log(loginData);
esse comentário e o console.log também

2024-07-15 18:21 UTC, ivancrneto commented on frontend/src/UserSettings.jsx
> +              "Authorization": "Token cc667d866d62ce770fd90736daa5a8a36d6db6cd",
const loginData = localStorage.getItem('loginData');

```suggestion
              "Authorization": "Token " + loginData.token,
```

2024-07-30 19:11 UTC, Kauannery commented
Closing Pr for new Pr, rebase here

2024-07-30 19:11 UTC, closed without merging